app:
  baseUrl: https://useinsider.com/careers/open-positions/?department=qualityassurance
  select: chrome
  driver:
    path: externals/drivers/chromedriver.exe
    type: webdriver.chrome.driver
    driverClass: org.openqa.selenium.chrome.ChromeDriver
  driverFirefox:
    path: externals/drivers/geckodriver.exe
    type: webdriver.gecko.driver
    driverClass: org.openqa.selenium.firefox.FirefoxDriver
